spring.application.name=spapp.api


spring.datasource.url=jdbc:sqlserver://localhost;instanceName=MSSQLLocalDB;databaseName=SPAPP;trustServerCertificate=true;encrypt=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=sa
spring.datasource.password=SPAPP123


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect