spring.application.name=spapp.api

spring.datasource.url=Data Source=(localdb)\MSSQLLocalDB;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=False;Application Name="Microsoft SQL Server Management Studio - Query";Command Timeout=0
spring.datasource.username=sa
spring.datasource.password=SPAPP123

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Dialeto SQL Server
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect